wake_words = ["Weebo", "wei", "weber", "we", "Weaver"]
global_lang = "en-us"
speech_service = "amazon" # google
aws_voice_id = "Salli" #Lotte for Dutch.
aws_speech_sample_rate = 22050
api_ai_access_token = "3f0d3c6c8d1d4af6a21f2475c8935de6"
aws_key_id = "AKIAIM44WOQ2ENEXDVCA"
aws_secret_key = "nCOXl7f3393bTOvY0eEHcyzYFtg57IC/ahbl+EK2"
wolfram_alpha_id = "TYX4Q4-VG8YW8YL4T"
tmp_speech_file = "/var/tmp/tmp_speech.mp3"
