"""empty message

Revision ID: 0ed01bfe41c0
Revises: 33f73ed6e117
Create Date: 2017-08-19 12:39:07.950642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed01bfe41c0'
down_revision = '33f73ed6e117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarms', sa.Column('alarm_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarms', 'alarm_time')
    # ### end Alembic commands ###
