"""empty message

Revision ID: e8bc23429da2
Revises: 7202f7c152ff
Create Date: 2017-08-19 13:23:25.748395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8bc23429da2'
down_revision = '7202f7c152ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
